# -*- coding: utf-8 -*-
"""escape char.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eicaZe5IKxrAtahy7uZc8rB_ZdIIgj6u
"""



print('dia berkata : "pergilah!"')

print("aku menimpali: \"apakah kau ingin aku 'angkat kaki?!\'")

("\\(^-^)/(\\-_-/)")

