# -*- coding: utf-8 -*-
"""rafha079

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AsAu6495kVeusZ-qZbX6V7Q9O55Bm6jZ
"""

nama = 'ahmad gg'
asal = 'lampung'

print(nama)

print(asal)

print(nama + asal)

print('halo','nama saya', nama)

print('halo','nama saya', nama,'asal saya dari', asal)

data_lengkap = nama, asal

print(data_lengkap)

"""STRING + non **SSTRING**"""

asal_kota = 'bandar lampung'
kode_pos = 45171

asal_kota_kode_pos = asal_kota + str(kode_pos)

print(asal_kota_kode_pos)

