# -*- coding: utf-8 -*-
"""string 10 maret

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zon7DGe5mMLdjrghTfZlxoROg_ubtfKO
"""

template = 'halo, saya %s dari %s'

print(template % ('lendis fabri', 'indonesia'))

template = 'halo, saya {nama} dari {asal}'
template_2 = 'saya suka makan {} dan minum {}'

print(template.format(nama = 'lendis fabri', asal = 'indonesia'))

nama = 'Rafha'
asal = 'indonesia'

print(f'perkenalkan saya {nama} dari {asal} XD')



"""**LIST**"""

alamat ='surabaya, jawa timur, indonesia'

print(alamat.split())
['surabaya,', 'jawa', 'timur,', 'indonesia']



"""**joinm**"""

print('<3'.join(['aku', 'suka','python']))

print('halo selamat pagi!'.upper())
print('Halo Selamat Siang!'.upper())

print('APA KABAR!'.lower())
print('Lagi Dimana!'.lower())

print('daun tidak pernah membenci angin'.title())
print('ANJAY'.title())

print('Indonesia Adalah Negaraku'.swapcase())
print('aKu CiNtA iNdOmIe'.swapcase())

angka = '12345'

print('indeks angka 3:',angka.find('3'))
print('indeks angka 45:',angka.find('45'))
print('indeks angka 35:',angka.find('35'))

asal = 'lampung'

print(asal.find('pung'))

ibu_kota = 'jakarta'

print(ibu_kota.replace('a', 'i'))
print(ibu_kota.replace('kar', '20290202900290020'))
print(ibu_kota.replace('a', ''))

paragraf = 'baru-baru ini telah ditemukan sebuah meteor di suatu sungai di malam hari dikala senja'
x = paragraf.count('di')

print(f'kata "di" muncul sebanyak {x} kali')

